

CC = gcc
FLAGS = -I ./NtyCo/core/ -L ./NtyCo/ -lntyco -luring
TARGET = kvstore

SRCS = kvstore.c ntyco.c proactor.c kvs_array.c kvs_rbtree.c
# INC = -I ./NtyCo/core/
# LIBS = -L ./NtyCo/ -lntyco -luring
# FLAGS = -I ./NtyCo/core/ -L ./NtyCo/ -lntyco -luring

OBJS = $(SRCS:.c=.o)
TESTCASE = testcase 
SUBDIR = ./NtyCo/

all: $(SUBDIR) $(TARGET) # $(TESTCASE)

$(SUBDIR): ECHO 
	make -C $@

ECHO:
	@echo $(SUBDIR)

$(TARGET): $(OBJS) 
	$(CC) -o $@ $^ $(FLAGS)

clean:
	rm -rf kvstore *.o

